#### Задание 1

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6], 
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.4])

#### Задание 2

In [4]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Задание 3

In [5]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp

8.0

In [6]:
a_cov = a_centered_sp / (a_centered.shape[0] - 1)

#### Задание 4**

In [7]:
np_cov = np.cov(a_centered.T)[0, 1]
np_cov

2.0

In [8]:
np_cov == a_cov

True